# Generated by Django 5.0.3 on 2024-08-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
