# Generated by Django 5.0.3 on 2024-08-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_blogs_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_accepted',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
