# Generated by Django 5.0.3 on 2024-09-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
