# Generated by Django 5.0.3 on 2024-04-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_content_message_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_status',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Start', 'Start')], default='Nothing', max_length=20),
        ),
    ]
