# Generated by Django 5.0.3 on 2024-04-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_message_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.AddField(
            model_name='message',
            name='messages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
