# Generated by Django 5.0.3 on 2024-04-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_remove_message_body_message_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
