# Generated by Django 5.1.2 on 2024-11-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
