# Generated by Django 5.1.1 on 2025-01-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorqrcode',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
