# Generated by Django 5.1.1 on 2024-11-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_image', models.ImageField(blank=True, null=True, upload_to='service/')),
            ],
        ),
    ]
