# Generated by Django 5.0.3 on 2024-06-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producebuy',
            name='buying_status',
            field=models.CharField(blank=True, choices=[('BuyInProgress', 'BuyInProgress'), ('PaymentDone', 'PaymentDone'), ('BuyCompleted', 'BuyCompleted'), ('BuyRejected', 'BuyRejected')], max_length=20, null=True),
        ),
    ]
