# Generated by Django 5.1.1 on 2024-10-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduce',
            name='ammount_in_green_points',
        ),
        migrations.AddField(
            model_name='sellproduce',
            name='amount_in_green_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellproduce',
            name='product_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellproduce',
            name='product_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
