# Generated by Django 5.1.1 on 2024-11-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_mediagallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediagallery',
            name='media_image',
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='media_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
