# Generated by Django 5.1.1 on 2024-10-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_categoryforservices_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sp_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_common.serviceproviderdetails'),
        ),
    ]
