# Generated by Django 5.1.1 on 2025-01-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_vendorqrcode_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorqrcode',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='vendorqrcode',
            name='type',
            field=models.CharField(choices=[('Select', 'Select'), ('Deselect', 'Deselect')], default='Deselect', max_length=10),
        ),
    ]
