# Generated by Django 5.1.1 on 2024-10-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_remove_sellproduce_ammount_in_green_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
    ]
