# Generated by Django 5.0.3 on 2024-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetails',
            name='business_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
