# Generated by Django 5.1.2 on 2024-12-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_order_payment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfromvendor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
