# Generated by Django 4.2 on 2023-12-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_room_remove_user_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255),
        ),
    ]
