# Generated by Django 4.2 on 2023-12-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_alter_room_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
