# Generated by Django 5.1.1 on 2024-10-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_service_sp_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
    ]
