# Generated by Django 5.0.3 on 2024-06-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_booking_review_service_booking_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='price_per_hour',
        ),
    ]
