# Generated by Django 5.0.3 on 2024-09-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_alter_vendordetails_business_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryForProduces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
