# Generated by Django 5.0.7 on 2025-01-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_remove_vendorqrcode_is_selected_vendorqrcode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderdetails',
            name='average_cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
