# Generated by Django 5.1.1 on 2024-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_remove_mediagallery_media_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediagallery',
            name='media_images',
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='media_image',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
    ]
