# Generated by Django 5.0.3 on 2024-08-23 10:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_productfromvendor_cgst_productfromvendor_gst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfromvendor',
            name='taxable_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productfromvendor',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productfromvendor',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
