# Generated by Django 5.0.3 on 2024-08-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_productfromvendor_taxable_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
