# Generated by Django 4.2 on 2023-12-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
