# Generated by Django 5.0.3 on 2024-09-23 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_categoryforproduces'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduce',
            name='produce_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_common.categoryforproduces'),
        ),
    ]
