# Generated by Django 5.0.7 on 2025-01-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_serviceproviderdetails_average_cost_per_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price_per_hour',
            new_name='price_per_basis',
        ),
    ]
