# Generated by Django 5.1.1 on 2024-11-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_remove_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='basis',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Monthly', 'Monthly')], default='Hourly', max_length=255),
        ),
    ]
