# Generated by Django 4.2 on 2023-12-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_adminincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
