# Generated by Django 5.0.3 on 2024-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
