# Generated by Django 5.1.1 on 2024-11-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_service_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount_percentage_for_greencoins',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='basis',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Monthly', 'Monthly'), ('Service-based', 'Service-based')], default='Hourly', max_length=255),
        ),
    ]
