# Generated by Django 5.0.3 on 2024-09-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_sellproduce_produce_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_query',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
