# Generated by Django 5.0.7 on 2025-01-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_rename_price_per_hour_service_price_per_basis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price_per_basis',
            new_name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='serviceproviderdetails',
            name='average_cost_per_hour',
        ),
    ]
