# Generated by Django 5.1.1 on 2024-11-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_newsactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsactivity',
            name='date_of_news_or_event',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsactivity',
            name='type',
            field=models.CharField(choices=[('News', 'News'), ('Event', 'Event')], default='News', max_length=10),
        ),
    ]
