# Generated by Django 5.0.7 on 2025-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0006_rename_price_per_basis_service_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardeningprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gardeningprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
