# Generated by Django 5.1.1 on 2024-11-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0006_service_discount_percentage_for_greencoins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='green_coins_required',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
