# Generated by Django 4.2 on 2024-01-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0006_alter_user_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_game_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
