# Generated by Django 5.1.1 on 2024-11-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0006_newsactivity_date_of_news_or_event_newsactivity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsactivity',
            name='author',
        ),
    ]
