# Generated by Django 5.1.2 on 2025-01-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0007_gardeningprofile_latitude_gardeningprofile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsactivity',
            name='type',
            field=models.CharField(choices=[('News', 'News'), ('Activity', 'Activity')], default='News', max_length=10),
        ),
    ]
