# Generated by Django 4.2 on 2024-01-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0007_user_is_game_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
