# Generated by Django 5.1.1 on 2024-11-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0007_remove_newsactivity_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorQRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='vendor_qr_codes/')),
            ],
        ),
    ]
