# Generated by Django 4.2 on 2024-01-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0008_rename_email_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
