# Generated by Django 5.1.1 on 2024-11-19 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0008_vendorqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorqrcode',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
