# Generated by Django 5.1.2 on 2025-01-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0008_alter_newsactivity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediagallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
