# Generated by Django 5.1.2 on 2025-01-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0009_mediagallery_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('rejection_reason', models.TextField()),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
