# Generated by Django 5.0.3 on 2024-03-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0010_remove_user_is_game_organizer_user_email_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
