# Generated by Django 5.1.2 on 2025-01-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0010_rejecteduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RejectedUser',
        ),
        migrations.AddField(
            model_name='user',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
