# Generated by Django 5.1.1 on 2024-11-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0011_alter_productfromvendor_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfromvendor',
            name='payment_receipt',
        ),
    ]
