# Generated by Django 5.0.3 on 2024-03-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0012_alter_user_is_active_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
    ]
