# Generated by Django 5.1.1 on 2024-11-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0012_remove_productfromvendor_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfromvendor',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
