# Generated by Django 5.1.1 on 2024-11-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0014_paymentscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.DeleteModel(
            name='PaymentScreenshot',
        ),
    ]
