# Generated by Django 5.0.3 on 2024-04-01 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0014_remove_user_username_user_address_user_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardeningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden_area', models.BigIntegerField(blank=True, default=0, null=True)),
                ('number_of_plants', models.BigIntegerField(blank=True, default=0, null=True)),
                ('number_of_unique_plants', models.BigIntegerField(blank=True, default=0, null=True)),
                ('garden_image', models.ImageField(blank=True, null=True, upload_to='garden/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
