# Generated by Django 5.1.1 on 2024-11-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0015_order_payment_screenshot_delete_paymentscreenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfromvendor',
            name='payment_receipt',
        ),
    ]
