# Generated by Django 5.0.3 on 2024-04-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0016_gardenquizmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='GardenQuizModel',
        ),
    ]
