# Generated by Django 5.0.3 on 2024-04-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0019_alter_wallet_trasnsaction_history_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet_trasnsaction_history',
            name='history',
            field=models.JSONField(default=dict),
        ),
    ]
