# Generated by Django 5.0.3 on 2024-04-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0023_gardeningmodelupdatereject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivityrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='is_accepted',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserActivityReject',
        ),
        migrations.DeleteModel(
            name='UserActivityRequest',
        ),
    ]
