# Generated by Django 5.0.3 on 2024-04-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0024_remove_useractivityrequest_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GardeningModel',
            new_name='GardeningProfile',
        ),
        migrations.RenameModel(
            old_name='GardeningModelUpdateReject',
            new_name='GardeningProfileUpdateReject',
        ),
        migrations.RenameModel(
            old_name='GardeningModelUpdateRequest',
            new_name='GardeningProfileUpdateRequest',
        ),
    ]
