# Generated by Django 5.0.3 on 2024-04-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0025_rename_gardeningmodel_gardeningprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardeningprofileupdaterequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='gardeningprofileupdaterequest',
            name='changes',
            field=models.JSONField(default=dict),
        ),
    ]
