# Generated by Django 5.0.3 on 2024-04-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0026_remove_gardeningprofileupdaterequest_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardeningprofileupdaterequest',
            name='changes',
            field=models.TextField(),
        ),
    ]
