# Generated by Django 5.0.3 on 2024-04-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0027_alter_gardeningprofileupdaterequest_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='activity_title',
            field=models.CharField(blank=True, default='No Title', max_length=250, null=True),
        ),
    ]
