# Generated by Django 5.0.3 on 2024-04-04 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0028_useractivity_activity_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellProduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='No Title', max_length=250, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='productforsell/')),
                ('product_quantity', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=10)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
