# Generated by Django 5.0.3 on 2024-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0029_sellproduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduce',
            name='SI_units',
            field=models.CharField(choices=[('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Liter', 'Liter')], default='Kilogram', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellproduce',
            name='product_quantity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
