# Generated by Django 5.0.3 on 2024-04-04 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0030_sellproduce_si_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduce',
            name='ammount_in_green_points',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
