# Generated by Django 5.0.3 on 2024-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0031_sellproduce_ammount_in_green_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduce',
            name='ammount_in_green_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
