# Generated by Django 5.0.3 on 2024-04-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0032_alter_sellproduce_ammount_in_green_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('Bhubaneswar', 'Bhubaneswar'), ('Cuttack', 'Cuttack'), ('Brahmapur', 'Brahmapur'), ('Puri', 'Puri'), ('Balasore', 'Balasore')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
