# Generated by Django 5.0.3 on 2024-04-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0034_user_facebook_link_user_instagram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='whatsapp_link',
        ),
    ]
