# Generated by Django 5.0.3 on 2024-04-08 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0035_remove_user_whatsapp_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('SI_units', models.CharField(choices=[('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Liter', 'Liter')], default='Kilogram', max_length=20)),
                ('ammount_in_green_points', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buying_user', to=settings.AUTH_USER_MODEL)),
                ('sell_produce', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='app_common.sellproduce')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='selling_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
