# Generated by Django 5.0.3 on 2024-04-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0036_producebuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producebuy',
            name='sell_produce',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
