# Generated by Django 5.0.3 on 2024-04-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0037_alter_producebuy_sell_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_invest',
            field=models.FloatField(default=0.0),
        ),
    ]
