# Generated by Django 5.0.3 on 2024-04-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0038_user_total_income_user_total_invest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet_trasnsaction_history',
            name='user_pk',
        ),
    ]
