# Generated by Django 5.0.3 on 2024-04-09 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0039_remove_wallet_trasnsaction_history_user_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producebuy',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producebuy',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
