# Generated by Django 5.0.3 on 2024-04-09 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0040_alter_producebuy_buyer_alter_producebuy_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producebuy',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buying_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producebuy',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selling_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
