# Generated by Django 5.0.3 on 2024-04-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0041_alter_producebuy_buyer_alter_producebuy_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet_Trasnsaction_History',
        ),
    ]
