# Generated by Django 5.0.3 on 2024-04-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0042_delete_wallet_trasnsaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='producebuy',
            name='buying_status',
            field=models.CharField(blank=True, choices=[('BuyInProgress', 'BuyInProgress'), ('BuyCompleted', 'BuyCompleted'), ('BuyRejected', 'BuyRejected')], max_length=20, null=True),
        ),
    ]
