# Generated by Django 5.0.3 on 2024-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0043_producebuy_buying_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduce',
            name='validity_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellproduce',
            name='SI_units',
            field=models.CharField(blank=True, choices=[('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Liter', 'Liter'), ('Units', 'Units')], max_length=20, null=True),
        ),
    ]
