# Generated by Django 5.0.3 on 2024-04-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0044_sellproduce_validity_duration_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellproduce',
            old_name='reject_reason',
            new_name='reason',
        ),
    ]
