# Generated by Django 5.0.3 on 2024-04-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0045_rename_reject_reason_sellproduce_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduce',
            name='validity_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
