# Generated by Django 5.0.3 on 2024-04-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0046_sellproduce_validity_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='producebuy',
            name='payment_link',
            field=models.CharField(choices=[('Send', 'Send'), ('NotAvailable', 'NotAvailable')], default='NotAvailable', max_length=20),
        ),
    ]
