# Generated by Django 5.0.3 on 2024-04-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0047_producebuy_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producebuy',
            name='sell_produce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_common.sellproduce'),
        ),
    ]
