# Generated by Django 5.0.3 on 2024-04-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0048_alter_producebuy_sell_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='producebuy',
            name='product_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='producebuy',
            name='sell_produce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_common.sellproduce'),
        ),
    ]
