# Generated by Django 5.0.3 on 2024-04-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0049_producebuy_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producebuy',
            name='quantuty_buyer_want',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
