# Generated by Django 5.0.3 on 2024-04-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0050_producebuy_quantuty_buyer_want'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producebuy',
            old_name='quantuty_buyer_want',
            new_name='quantity_buyer_want',
        ),
        migrations.AddField(
            model_name='producebuy',
            name='ammount_based_on_quantity_buyer_want',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
