# Generated by Django 5.0.3 on 2024-05-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0051_rename_quantuty_buyer_want_producebuy_quantity_buyer_want_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='comments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='likes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
