# Generated by Django 5.0.3 on 2024-05-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0053_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AddField(
            model_name='user',
            name='ratings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
