# Generated by Django 5.0.3 on 2024-05-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0054_remove_user_rating_user_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_gardener',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
