# Generated by Django 5.0.3 on 2024-05-21 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0055_user_is_gardener_user_is_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.CharField(max_length=255)),
                ('business_description', models.TextField()),
                ('business_license_number', models.CharField(max_length=50)),
                ('business_category', models.CharField(choices=[('plants', 'Plants'), ('tools', 'Tools'), ('seeds', 'Seeds'), ('other', 'Other')], max_length=20)),
                ('establishment_year', models.PositiveIntegerField()),
                ('website', models.URLField(blank=True)),
                ('established_by', models.CharField(blank=True, max_length=100)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
