# Generated by Django 5.0.3 on 2024-05-22 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0056_vendordetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFromVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_products/')),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('seeds', 'Seeds'), ('plants', 'Plants'), ('tools', 'Gardening Tools'), ('fertilizers', 'Fertilizers'), ('pots_containers', 'Pots & Containers'), ('pest_control', 'Pest Control'), ('irrigation', 'Irrigation Systems'), ('garden_decor', 'Garden Decor')], max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
