# Generated by Django 5.0.3 on 2024-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0057_productfromvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfromvendor',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
