# Generated by Django 5.0.3 on 2024-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0058_productfromvendor_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfromvendor',
            name='price',
        ),
        migrations.AddField(
            model_name='productfromvendor',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productfromvendor',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
