# Generated by Django 5.0.3 on 2024-05-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0059_remove_productfromvendor_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfromvendor',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
