# Generated by Django 5.0.3 on 2024-05-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0060_productfromvendor_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfromvendor',
            old_name='quantity',
            new_name='stock',
        ),
    ]
