# Generated by Django 5.0.3 on 2024-05-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0062_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producebuy',
            name='ammount_in_green_points',
        ),
        migrations.RemoveField(
            model_name='producebuy',
            name='product_quantity',
        ),
    ]
