# Generated by Django 5.0.3 on 2024-05-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0063_remove_producebuy_ammount_in_green_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producebuy',
            name='rating_given',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
