# Generated by Django 5.0.3 on 2024-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0066_remove_order_created_at_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rtg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_serviceprovider',
            field=models.BooleanField(default=False),
        ),
    ]
