# Generated by Django 5.0.3 on 2024-05-31 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0067_user_is_rtg_user_is_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Lawn Care', 'Lawn Care'), ('Tree Trimming', 'Tree Trimming'), ('Garden Design', 'Garden Design'), ('Irrigation Systems', 'Irrigation Systems')], max_length=50)),
                ('service_area', models.CharField(max_length=255)),
                ('average_cost_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('years_experience', models.IntegerField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
