# Generated by Django 5.0.3 on 2024-05-31 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0068_serviceproviderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderdetails',
            name='service_area',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceproviderdetails',
            name='service_type',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='GardenerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_for', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('years_experience', models.IntegerField()),
                ('available_days', models.TextField()),
                ('willing_to_travel', models.BooleanField(default=False)),
                ('gardener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
