# Generated by Django 5.0.3 on 2024-05-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0069_alter_serviceproviderdetails_service_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenerdetails',
            name='willing_to_travel',
        ),
    ]
