# Generated by Django 5.0.3 on 2024-06-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0070_remove_gardenerdetails_willing_to_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_gardener',
        ),
        migrations.DeleteModel(
            name='GardenerDetails',
        ),
    ]
