# Generated by Django 5.0.3 on 2024-06-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0071_remove_user_is_gardener_delete_gardenerdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfromvendor',
            name='is_approved',
        ),
    ]
