# Generated by Django 5.0.3 on 2024-06-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0072_remove_productfromvendor_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfromvendor',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productfromvendor',
            name='green_coins_required',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
