# Generated by Django 5.0.3 on 2024-06-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0073_productfromvendor_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating_given',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productfromvendor',
            name='ratings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
