# Generated by Django 5.0.3 on 2024-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0074_order_rating_given_productfromvendor_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('On_Way', 'On_Way'), ('Refund', 'Refund'), ('Return', 'Return'), ('Delivered', 'Delivered')], default='Placed', max_length=255),
        ),
    ]
