# Generated by Django 5.0.3 on 2024-06-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0075_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfromvendor',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
